### ISSUE TITLE
YoutubeScrapers/API #available? should be public

### ISSUE THREAD

**Issue by glebm** [thibaudgg/video_info#173]
Forwarding to a private method generates a warning in ruby 2.4.0+ (as of https://github.com/ruby/ruby/commit/ef13e60fe07766549275c19f3e5112fb7773cf38), e.g.:

```console
> info.available?
forwardable.rb:157 forwarding to private method VideoInfo::Providers::Youtube#available?
```

**Comment by vheuken** [comment]
Thanks for the report. I'm going to have a look at this tonight.

**Comment by vheuken** [comment]
It looks like simply making `available?` public doesn't solve the warning. I'll investigate more.

**Comment by vheuken** [comment]
Simply making them public doesn't appear to solve it. I'll keep
investigating.

**Comment by vheuken** [comment]
Sorry, it looks like my last comment was due to a configuration issue on my end. I pushed the fix to master and I'll push a minor version sometime this week.

**Comment by Spone** [comment]
Hi, I still have this issue with the `video_info` gem version 2.7
